# Generated by Django 6.0.6 on 2026-06-17 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('products_app', '0002_brand_flavor_ingredient_order_product_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_firstname',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия покупателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя покупателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SH', 'Вывоз из магазина'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Способ доставки'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на позицию')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basket_items', to='basket.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basket_items', to='products_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='basket.Pos_order', to='products_app.product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
